(define (problem grounded-STRIPS-PSR-S9-N1-L4-F30)
(:domain grounded-STRIPS-PSR)
(:init (= (total-cost) 0)
(do-normal)
(NOT-UPDATED-CB1)
(NOT-CLOSED-SD2)
(NOT-CLOSED-SD5)
(CLOSED-SD7)
(CLOSED-SD6)
(CLOSED-SD4)
(CLOSED-SD3)
(CLOSED-SD1)
(CLOSED-CB1)
)
(:goal
(and
(do-normal)
(CLOSED-SD3)
(CLOSED-CB1)
(CLOSED-SD1)
(UPDATED-CB1)
)
)
(:metric minimize (total-cost))
)
